---
title: "Lab5 Data Visualization w ggplot"
author: "Blair Chang (PID_A59000602)"
format: pdf
editor: visual
---

## Using ggplot

```{r}
#To use ggplot2, we first need to install it on our computers. 
#To do this we will use the function `install.packages(ggplot2)`.
#Type it in Console! (one time install)

#Before I use any functions I have to load them up by calling library to start! like: 

library(ggplot2)

```

```{r}
head(cars, n=5)
# There is always the "base R" graphics system. i.e. `plot()`
plot(cars)
```

##To use ggplot I need 3 things:
```{r}
# 1. data (the stuff I wanna plot)
# 2. aesthetics aes() values - how data map to the points
# 3. geoms - how I wanna draw 


# put plus at the end of lines
ggplot(cars) + 
  aes(x=speed, y=dist) +
  geom_point() +
  labs(title="Speed and Stopping Distances of Cars",
       x="Speed (MPH)", 
       y="Stopping Distance (ft)",
       subtitle = "Blair's dream cars!",
       caption="Dataset: 'cars'")  +
  geom_smooth(method = "lm") + #linear
  theme_bw() # The classic dark-on-light ggplot2 theme.
```
```{r}
url <- "https://bioboot.github.io/bimm143_S20/class-material/up_down_expression.txt"
genes <- read.delim(url)
head(genes)
nrow(genes)
ncol(genes)
table(genes$State)
round( table(genes$State)/nrow(genes) * 100, 2 )
```
```{r}
p <- ggplot(genes) + 
  aes(x=Condition1, y=Condition2, col=State) +
  geom_point()
p

p + scale_colour_manual( values=c("cyan3","gray","coral3") ) +
labs(title="Gene Expresion Changes Upon Drug Treatment",
         x="Control (no drug) ",
         y="Drug Treatment")
```

```{r}
# install.packages("gapminder") in the Console
library(gapminder)
# File location online
url <- "https://raw.githubusercontent.com/jennybc/gapminder/master/inst/extdata/gapminder.tsv"

gapminder <- read.delim(url)

# install.packages("dplyr")
library(dplyr)

gapminder_2007 <- gapminder %>% filter(year==2007)

ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.5) +
  scale_size_area(max_size = 10)
```

```{r}
ggplot(gapminder_2007) + 
  aes(x=gdpPercap, y=lifeExp, color=continent, size=pop) +
  geom_point(alpha=0.8) +
  scale_size_area(max_size = 10)
```

```{r}
#Question 7:  Can you adapt the code you have learned thus far to reproduce our gapminder scatter plot for the year 1957? What do you notice about this plot is it easy to compare with the one for 2007?
gapminder_1957 <- gapminder %>% filter(year==1957)
ggplot(gapminder_1957) + 
  aes(x = gdpPercap, y = lifeExp, color=continent, size = pop) +
  geom_point(alpha=0.7) +
  scale_size_area(max_size = 15)

```
##Comparing ggplots
```{r}
#Comparing different years
gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)

ggplot(gapminder_1957) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop), alpha=0.9) + 
  scale_size_area(max_size = 12) +
  facet_wrap(~year)
```

```{r}
gapminder_top5 <- gapminder %>% 
  filter(year==2007) %>% 
  arrange(desc(pop)) %>% 
  top_n(5, pop)

gapminder_top5

ggplot(gapminder_top5) + 
  geom_col(aes(x = country, y = pop))

ggplot(gapminder_top5) + 
  geom_col(aes(x=country, y= lifeExp, fill=lifeExp))
```
```{r}
ggplot(gapminder_top5) +
  aes(x=reorder(country, -pop), y=pop, fill=country) +
  geom_col(col="gray30") +
  guides(fill="none")
```

```{r}
head(USArrests)
USArrests$State <- rownames(USArrests)
ggplot(USArrests) +
  aes(x=reorder(State,Murder), y=Murder) +
  geom_point() +
  geom_segment(aes(x=State,xend=State, y=0, 
                   yend=Murder), color="cornflowerblue") +
  coord_flip()
```
##Animation
```{r}
# install.packages("gganimate") and install.packages("gifski") in the Console
library(gapminder)
library(gganimate)
library(ggplot2)
# Setup nice regular ggplot of the gapminder data
ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, colour = country)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  scale_colour_manual(values = country_colors) +
  scale_size(range = c(2, 12)) +
  scale_x_log10() +
  # Facet by continent
  facet_wrap(~continent) +
  # Here comes the gganimate specific bits
  labs(title = 'Year: {frame_time}', x = 'GDP per capita', y = 'life expectancy') +
  transition_time(year) +
  shadow_wake(wake_length = 0.1, alpha = FALSE)
```
```{r}
#install.packages('patchwork') 

library(patchwork)
# Setup some example plots 
p1 <- ggplot(mtcars) + geom_point(aes(mpg, disp))
p2 <- ggplot(mtcars) + geom_boxplot(aes(gear, disp, group = gear))
p3 <- ggplot(mtcars) + geom_smooth(aes(disp, qsec))
p4 <- ggplot(mtcars) + geom_bar(aes(carb))

# Use patchwork to combine them here:
(p1 | p2 | p3) / p4
```

```{r}
sessionInfo()
```

