theme: jekyll-theme-minimal
logo: https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.dribbble.com%2Fusers%2F3093%2Fscreenshots%2F1662859%2Fmedia%2F86a28616cbfac8d80a045ee472edd0ae.png&tbnid=TXjeYcEgTMEf-M&vet=12ahUKEwicxqyK8ICDAxVONEQIHZ8TBFUQMygyegUIARDaAQ..i&imgrefurl=https%3A%2F%2Fdribbble.com%2Fshots%2F1662859-pac-man-ghost&docid=nfOiQXDesnn8FM&w=800&h=600&q=pac%20man%20ghost%20logo&ved=2ahUKEwicxqyK8ICDAxVONEQIHZ8TBFUQMygyegUIARDaAQ
title: Bioinformatics
